# Generated by Django 3.2.5 on 2021-11-02 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blood_Group', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District_Name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Division_Name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('Date_of_Birth', models.DateField()),
                ('PhoneNumber', models.CharField(max_length=15)),
                ('Gender', models.CharField(max_length=20)),
                ('Area', models.CharField(max_length=40)),
                ('Postal_Code', models.IntegerField()),
                ('last_donate_date', models.CharField(blank=True, max_length=50, null=True)),
                ('any_disease', models.CharField(blank=True, max_length=50, null=True)),
                ('Blood_Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood', to='account.blood')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district', to='account.district')),
                ('Division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division', to='account.division')),
            ],
        ),
    ]
