# Generated by Django 3.2.5 on 2021-11-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211103_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Area',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='Gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='any_disease',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
