# Generated by Django 3.2.5 on 2021-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20211104_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='any_disease',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
