# Generated by Django 3.2.5 on 2021-11-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_any_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CPassword',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='any_disease',
            field=models.CharField(max_length=20),
        ),
    ]
