# Generated by Django 3.2.5 on 2021-11-04 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211104_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='CPassword',
            new_name='Confirm_Password',
        ),
    ]
