# Generated by Django 3.2.5 on 2021-11-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_cpassword_user_confirm_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Blood_Group',
        ),
        migrations.RemoveField(
            model_name='user',
            name='District',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Division',
        ),
        migrations.DeleteModel(
            name='Blood',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='division',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
