# Generated by Django 3.2.7 on 2022-09-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_hotelbooking_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='booking_status',
        ),
    ]
