# Generated by Django 3.2.7 on 2022-09-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_remove_hotelbooking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelbooking',
            name='booking_status',
            field=models.CharField(default='Booked', max_length=10),
        ),
    ]
