# Generated by Django 3.2.5 on 2021-11-05 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Area',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Blood_Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood', to='User.blood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Date_of_Birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='User.district'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division', to='User.division'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='PhoneNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Postal_Code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='any_disease',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_donate_date',
            field=models.DateField(null=True),
        ),
    ]
