# Generated by Django 3.2.5 on 2021-11-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20211106_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='profiles/default.png', null=True, upload_to='profiles/'),
        ),
    ]
