# Generated by Django 3.2.5 on 2021-11-06 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20211106_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Blood_Group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood', to='User.blood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='District',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district', to='User.district'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='division', to='User.division'),
        ),
    ]
